name: Format
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v9
        with:
          pattern: |
            src/**/*.hs
            test/**/*.hs
